export const STATES = [
  { name: "" },
  { name: "Abia", id: "0" },
  { name: "Adamawa", id: "1" },
  { name: "Akwa Ibom", id: "2" },
  { name: "Anambra", id: "3" },
  { name: "Bauchi", id: "4" },
  { name: "Bayelsa", id: "5" },
  { name: "Benue", id: "6" },
  { name: "Borno", id: "7" },
  { name: "Cross River", id: "8" },
  { name: "Delta", id: "9" },
  { name: "Ebonyi", id: "10" },
  { name: "Edo", id: "11" },
  { name: "Ekiti", id: "12" },
  { name: "Enugu", id: "13" },
  { name: "FCT - Abuja", id: "14" },
  { name: "Gombe", id: "15" },
  { name: "Imo", id: "16" },
  { name: "Jigawa", id: "17" },
  { name: "Kaduna", id: "18" },
  { name: "Kano", id: "19" },
  { name: "Katsina", id: "20" },
  { name: "Kebbi", id: "21" },
  { name: "Kogi", id: "22" },
  { name: "Kwara", id: "23" },
  { name: "Lagos", id: "24" },
  { name: "Nasarawa", id: "25" },
  { name: "Niger", id: "26" },
  { name: "Ogun", id: "27" },
  { name: "Ondo", id: "28" },
  { name: "Osun", id: "29" },
  { name: "Oyo", id: "30" },
  { name: "Plateau", id: "31" },
  { name: "Rivers", id: "32" },
  { name: "Sokoto", id: "33" },
  { name: "Taraba", id: "34" },
  { name: "Yobe", id: "35" },
  { name: "Zamfara", id: "36" },
];
